import pandas as pd
import numpy as np
import time
from langchain_openai import OpenAIEmbeddings
from sqlalchemy import text
from src.database import DatabaseManager, ProductCatalog, ShippedRaw, ConcessionRaw
from src.config import Config
from loguru import logger

BATCH_SIZE = 100 
DB_CHUNK_SIZE = 5000 

def clean_column_names(df: pd.DataFrame) -> pd.DataFrame:
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('__', '_')
    return df

def keep_valid_columns(df: pd.DataFrame, model_class) -> pd.DataFrame:
    valid_cols = set(c.name for c in model_class.__table__.columns)
    present_valid_cols = [c for c in df.columns if c in valid_cols]
    return df[present_valid_cols]

def generate_embeddings(texts: list) -> list:
    embeddings_model = OpenAIEmbeddings(model="text-embedding-3-small", api_key=Config.OPENAI_API_KEY)
    results = []
    for i in range(0, len(texts), BATCH_SIZE):
        batch = texts[i:i + BATCH_SIZE]
        try:
            logger.info(f"Vectorizing batch {i} to {i+len(batch)}...")
            results.extend(embeddings_model.embed_documents(batch))
            time.sleep(0.2) 
        except Exception as e:
            logger.error(f"Embedding error: {e}")
            results.extend([[0.0]*1536 for _ in range(len(batch))])
    return results

def run_smart_ingestion():
    db = DatabaseManager()
    db.init_db()
    session = db.get_session()
    
    logger.info("--- Starting Hybrid Ingestion ---")

    # 1. LOAD DATA
    try:
        ship_df = pd.read_csv("data/shipped_data.tsv", sep='\t', on_bad_lines='skip', low_memory=False)
        conc_df = pd.read_csv("data/concession_data.tsv", sep='\t', on_bad_lines='skip', low_memory=False)
        ship_df = clean_column_names(ship_df)
        conc_df = clean_column_names(conc_df)
    except Exception as e:
        logger.error(f"File Error: {e}")
        return

    # 2. PRODUCT CATALOG (Vector + Text Search)
    cols = ['asin', 'item_name', 'brand_name', 'manufacturer_name', 'subcategory_description']
    ship_cols = [c for c in cols if c in ship_df.columns]
    conc_cols = [c for c in cols if c in conc_df.columns]
    
    all_products = pd.concat([ship_df[ship_cols], conc_df[conc_cols]], ignore_index=True)
    unique = all_products.drop_duplicates(subset=['asin']).fillna("Unknown")
    
    # Check existing
    existing = set(row[0] for row in session.query(ProductCatalog.asin).all())
    new_prods = unique[~unique['asin'].isin(existing)]
    
    if not new_prods.empty:
        logger.info(f"Indexing {len(new_prods)} new products...")
        
        # Vectors
        txts = (new_prods['brand_name'].astype(str) + " " + new_prods['item_name'].astype(str)).tolist()
        vectors = generate_embeddings(txts)
        
        entries = []
        for (idx, row), vec in zip(new_prods.iterrows(), vectors):
            entries.append(ProductCatalog(
                asin=str(row['asin']),
                item_name=str(row['item_name'])[:5000],
                brand_name=str(row.get('brand_name', 'Unknown')),
                manufacturer_name=str(row.get('manufacturer_name', 'Unknown')),
                subcategory_description=str(row.get('subcategory_description', 'Unknown')),
                embedding=vec
                # search_vector is auto-generated by DB trigger below
            ))
        
        try:
            session.bulk_save_objects(entries)
            session.commit()
            
            # --- CRITICAL: Update Full-Text Search Index ---
            logger.info("Updating Keyword Search Index...")
            session.execute(text("""
                UPDATE product_catalog 
                SET search_vector = to_tsvector('english', brand_name || ' ' || item_name || ' ' || subcategory_description)
                WHERE search_vector IS NULL;
            """))
            session.commit()
            logger.success(f"Indexed {len(entries)} products (Vector + Keywords).")
        except Exception as e:
            session.rollback()
            logger.error(f"Catalog Error: {e}")
    else:
        logger.info("Catalog up to date.")

    # 3. TRANSACTIONS
    logger.info("Loading Transactions...")
    try:
        with db.engine.connect() as conn:
            conn.execute(text("TRUNCATE TABLE shipped_raw, concession_raw RESTART IDENTITY"))
            conn.commit()
            
        if 'fulfillment_channel' in ship_df.columns:
            ship_df.loc[ship_df['fulfillment_channel'] == 'FBA', 'shipped_cogs'] = 0
            
        keep_valid_columns(ship_df, ShippedRaw).to_sql('shipped_raw', db.engine, if_exists='append', index=False, chunksize=DB_CHUNK_SIZE)
        keep_valid_columns(conc_df, ConcessionRaw).to_sql('concession_raw', db.engine, if_exists='append', index=False, chunksize=DB_CHUNK_SIZE)
        logger.success("Transactions Loaded.")
    except Exception as e:
        logger.error(f"Transaction Load Error: {e}")

if __name__ == "__main__":
    run_smart_ingestion()